export const GET_TECHNOLOGIES = "GET_TECHNOLOGIES";
export const ADD_TECHNOLOGY = "ADD_TECHNOLOGY";
export const DELETE_TECHNOLOGY = "DELETE_TECHNOLOGY";
export const UPDATE_TECHNOLOGY = "UPDATE_TECHNOLOGY";
